name: osloturen-2019
channels:
  - defaults
  - conda-forge
dependencies:
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - plotly
  - ipykernel
  - beautifulsoup4
  - rise
  - scikit-plot
  - pip:
    - termcolor
    - wordcloud
    - stop-words
    - eli5
